project:
  type: website

website:
  title: "Beneath the surface 🌊"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: 
      dark: cyborg
      light: yeti
    css: styles.css
    toc: true



