---
title: "Developing Beneath the surface"
description: |
  About the developing of this website.
date: 2024-04-19
draft: false
---

### EN

### ES

# Desarrollando 'Beneath the surface 游깱'

## La idea

Lo primero que lleg칩 a mi mente fue 춺쯗e qu칠 manera puedo desarrollar una p치gina en que pueda dejar como referencia para aquellos que quisieran contactar conmigo en un ambiente profesional?췉 y 춺쯗esde qu칠 medio puedo compartir aquellas ideas, peque침os trabajos o experiencias personales que creo que podr칤an resultar de utilidad para otros profesionales en mi rubro?췉. Bueno, existen muchas opciones alrededor (redes sociales, podcast, TikTok, etc.). Esta primera decisi칩n no fue dif칤cil, pues no me caracterizo particularmente por mi carisma en redes, as칤 que decid칤 optar por escribir un blog. Sin embargo, aqu칤 la toma de decisiones s칤 se complic칩 un poco, pues existen muchas plataformas disponibles: [Wordpress](https://wordpress.com/), [Netlify](https://www.netlify.com/), [Gitlab pages](https://docs.gitlab.com/ee/user/project/pages/), [Medium](https://medium.com/), among [others](https://stackshare.io/github-pages/alternatives). Cada una plantea ventajas y potencialidades distintas, pero mi decisi칩n se bas칩 sobre todo en la familiaridad de uso de las plataformas [Github](https://github.com/) y [Quarto](https://quarto.org/). Me decid칤 por [Github pages](https://pages.github.com/).

## Github pages

Github pages es un servicio gratuito de alojamiento de sitios web est치ticos que permite publicar contenido HTML directamente desde un repositorio de GitHub. Esta plataforma ofrece m칰ltiples ventajas:

* **Gratuito**: No necesitas pagar por un servicio de alojamiento web, solo tener una cuenta de GitHub (gratuita).

* **F치cil de usar**: Subir tus archivos HTML, CSS y JavaScript a GitHub es muy sencillo.

* **Integraci칩n directa con GitHub**: Esto se hace MUY importante si ya usas GitHub (como fue mi caso) para tus proyectos de c칩digo.

* **Versionado**: GitHub Pages guarda un historial de todos los cambios que realices en tu sitio web, por lo que si algo sale mal siempre puedes volver a una versi칩n anterior de tu repositorio (p치gina).

* **Seguro**: GitHub Pages utiliza HTTPS para proteger tu sitio web.

* **R치pido**: Desde hace unos a침os, Microsoft compr칩 GitHub y por tanto sus servicios utilizan una extensa red global de servidores para entregar tu sitio web a los usuarios de todo el mundo.

* **Escalable**: GitHub Pages puede manejar cualquier cantidad de tr치fico, por lo que tu sitio web puede crecer sin problemas. Aunque de un blog personal/profesional no se espera tener picos de tr치fico muy altos, siempre es bueno saber que existe este respaldo. 

* **Optimizado para SEO**: GitHub Pages est치 optimizado para los motores de b칰squeda, lo que ayudar치 a que nuestro sitio web aparezca en los resultados de los principales buscadores web.

Al final, Github pages fue la opci칩n de alojamiento que me result칩 m치s atractiva. Sin embargo, existen m칰ltiples maneras de subir contenido, desde diferentes plataformas de desarrollo que involucran el uso de lenguajes de programaci칩n (e.g. Javascript) o de marcado, como markdown o Quarto. Una vez m치s, mi experiencia hist칩rica pes칩 m치s y me decant칠 por el uso de Quarto.

## Quarto

Quarto es una plataforma de publicaci칩n de documentos cient칤ficos de c칩digo abierto desarrollada por el equipo de POSIT (ex RStudio). Se basa en el formato R Markdown y lo ampl칤a con nuevas caracter칤sticas y funcionalidades para crear documentos m치s ricos e interactivos. Implementa un sistema de preprocesamiento m치s potente que R Markdown y soporta lenguajes de programaci칩n adicionales como Python y Julia, ampliando las posibilidades de an치lisis y visualizaci칩n.

Desde hace unos pocos a침os, he venido utilizando Quarto no solo para la redacci칩n de reportes sencillos en R, sino inclusive para la composici칩n completa de art칤culos cient칤ficos (uno de ellos con formato sometido directamente desde la salida en .docx obtenida en Quarto), as칤 como el desarrollo de webs interactivas a trav칠s de la dupla [Quarto-Shiny](https://quarto.org/docs/interactive/shiny/).

## Creando la p치gina

No tuve que empezar desde cero. Afortunadamente, hay mucho material all치 afuera, pero resumir칠 brevemente los principales links que utilic칠:

* Crear la website alojada en Github pages, preparada para el manejo de contenido con Quarto y trabajando desde RStudio: Los primeros pasos a seguir est치n muy bien explicados en el v칤deo de Melissa Van Bussel [(link)](https://quarto.org/docs/interactive/shiny/). Muy recomendable, aunque parte bajo el supuesto de que conocemos c칩mo manejar Git-bash y de que tenemos bien configurado un token para nuestra PC. Estos 칰ltimos detalles los colocar칠 al final de este art칤culo.

* Establecer un esquema de lo que vamos a publicar. Una vez que hayamos logrado configurar correctamente nuestra web, sigue el turno de tomar l치piz y papel y esquematizar qu칠 contenido deseamos compartir y cu치l ser치 la l칩gica para ordenar dicho contenido en secciones. Si bien esta parte es muy personal, ya que no ser치 lo mismo diagramar una p치gina que solo tiene como objetivo servir de referencia profesional (es decir, un CV interactivo) a la de un **freelancer** que desea mostrar sus principales proyectos y/o servicios ofrecidos, no necesitas ir desde cero tampoco. Puedes revisar ejemplos de p치ginas de otros creadores (investigadores, reporteros, bloggers, artistas gr치ficos, etc.) e inspirarte en sus dise침os. As칤 tambi칠n, puedes revisar ejemplos de estructuras de p치ginas que usan Github pages [(link)](https://jekyllthemes.io/free). Recuerda, todo debe partir SIEMPRE del tipo de contenido que planeas colocar. 

* Empezar a escribir. OK, esto no es un art칤culo cient칤fico y hay mucha m치s libertad para rellenar las distintas secciones; no obstante, recuerda siempre tener en cuenta los criterios b치sicos de redacci칩n (de lo general a lo espec칤fico), ser claro y cuidadoso al elegir el tipo de lenguaje (con base en el tipo de p칰blico que esperas que te lea) y, una vez m치s, revisar ejemplos. Por supuesto, en estos d칤as las plataformas de IA para generaci칩n de texto pueden resultar de gran ayuda, pero no debemos delegarles toda la carga (i.e. nada de copiar-pegar) sin antes leer corroborar la informaci칩n que nos devuelven. En este punto, me fueron de mucha utilidad los siguientes art칤culos:

  * Crear tu website con Quarto: tutorial completo y plantilla [link](https://www.marvinschmitt.com/blog/website-tutorial-quarto/).
  
  * Creando tu website personal con Quarto [link](https://ucsb-meds.github.io/creating-quarto-websites/).
  
  * Creando un website [link](https://quarto.org/docs/websites/).

* Establecer un orden. Una vez que hayamos culminado y publicado un primer art칤culo, todo ir치 siendo m치s simple en t칠rminos t칠cnicos ya que descubrir치s que existen m칰ltiples fuentes de referencia disponibles.

